name = "Better Compatibility Checker"
filename = "BetterCompatibilityChecker-1.1.14-build.26+mc1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3779/786/BetterCompatibilityChecker-1.1.14-build.26+mc1.18.2.jar"
hash-format = "sha1"
hash = "28c23a0d02e49eb6880100cd5ca69b396f1d62ed"

[update]
[update.curseforge]
file-id = 3779786
project-id = 551894
