name = "Caelus API (Forge)"
filename = "caelus-forge-1.18.1-3.0.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3650/485/caelus-forge-1.18.1-3.0.0.2.jar"
hash-format = "sha1"
hash = "befa3b8e7bd0f5fdf373be726e5ce2b7bdfa16b6"

[update]
[update.curseforge]
file-id = 3650485
project-id = 308989
