name = "Jade ğŸ”"
filename = "Jade-1.18.2-5.2.0.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "1be84831df2767ddc51504c6ae5973a6699cb5ae"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3803226
project-id = 324717
