name = "More Zombie Villagers (Forge)"
filename = "morezombievillagers_1.18.2-1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/204/morezombievillagers_1.18.2-1.6.jar"
hash-format = "sha1"
hash = "f04a2231095c9022bb11f66a74511b58034d7c01"

[update]
[update.curseforge]
file-id = 3669204
project-id = 347338
