name = "Pick Up Notifier [Forge]"
filename = "PickUpNotifier-v3.2.0-1.18.2-Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/364/PickUpNotifier-v3.2.0-1.18.2-Forge.jar"
hash-format = "sha1"
hash = "10960e9d8e924a7bb88661f5226c25f96dcc5213"

[update]
[update.curseforge]
file-id = 3671364
project-id = 351441
