name = "Snow Under Trees"
filename = "snowundertrees-1.18.2-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3694/488/snowundertrees-1.18.2-1.2.1.jar"
hash-format = "sha1"
hash = "eb93e79b6b7cdf93cb1258bacf469ba9a140de3b"

[update]
[update.curseforge]
file-id = 3694488
project-id = 353942
