name = "Supplementaries"
filename = "supplementaries-1.18.2-1.3.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3763/517/supplementaries-1.18.2-1.3.7.jar"
hash-format = "sha1"
hash = "51c87cfa4251fa3aa6a0c8049f6b4aebe6527ee2"

[update]
[update.curseforge]
file-id = 3763517
project-id = 412082
